### ISSUE TITLE
「Pandoc ユーザーズガイド 日本語版」を残す理由はあるのでしょうか？

### ISSUE THREAD

**Issue by HelloRusk** [pandoc-jp/pandoc-doc-ja#10]
Pandoc の日本語ドキュメントを Google 検索で探そうとすると、この GitHub Pages の他に、http://sky-y.github.io/site-pandoc-jp/users-guide/ というサイトも別に出てきます。こちらの方は古いバージョンの Pandoc の解説になっていますが、何か残すべき理由はあるのでしょうか？

もし特に理由が無いようでしたら、http://sky-y.github.io/site-pandoc-jp/ の方を

- 削除する
- こちらの方に 301 リダイレクトさせる（参考: https://blog.atusy.net/2019/03/11/use-cname-to-redirect-from-gh-pages/ ）
- canonical id を貼って URL 正規化する（参考: https://www.irep.co.jp/knowledge/blog/detail/id=46107/ ）

などした方が良いのではと思います。

**Comment by sky-y** [comment]
> 何か残すべき理由はあるのでしょうか？

ないです（私の怠惰です）。もし旧サイトのデータが必要なら、[旧GitHubリポジトリ](https://github.com/sky-y/site-pandoc-jp)の履歴やInternet Archiveなどから拾ってこれると思います。

先ほど、旧サイトにリダイレクトを仕込みました。下記URLから飛ぶとリダイレクトされると思います。

- http://sky-y.github.io/site-pandoc-jp/
- http://sky-y.github.io/site-pandoc-jp/users-guide/

下記の方法で対処しました。正確には301リダイレクトになっていないそうですが、簡易な方法のため採用しました。

[GItHub Pagesから他サイトへのリダイレクト設定をページ毎に行う (jekyll-redirect-from使用) - Qiita](https://qiita.com/ma2shita/items/d197d4dc6680547f04ba)

※ アンカーリンクには対応していません。

**Comment by HelloRusk** [comment]
ありがとうございます！
